services:
  #db:
  #  image: postgres:10.1
  web:
    build:
      context: .
      args:
        DEVEL: "yes"
    command: gunicorn --reload -b 0.0.0.0:8080 inspector.main:app
    env_file: dev/environment
    volumes:
      - .:/app/
    ports:
      - "80:8080"
    #links:
    #  - db
