name: Docker
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  build:
    name: Docker build (and optional push)
    runs-on: ubuntu-24.04
    env:
      RUBYGEMS_VERSION: "3.6.4"
      RUBY_VERSION: "3.4.2"
    permissions:
      id-token: write
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # master
      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        if: github.secret_source != 'None'
        with:
          role-to-assume: arn:aws:iam::048268392960:role/rubygems-ecr-pusher
          aws-region: us-west-2
      - name: Login to Amazon ECR
        if: github.secret_source != 'None'
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: "${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'true' }}"
          tags: |
            048268392960.dkr.ecr.us-west-2.amazonaws.com/rubygems/inspector:${{ github.sha }}
